### ISSUE TITLE
 Part Design → tree view / popup menu → Edit draft

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#164]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.28993 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 6d92e53)
Hash: 6d92e532bcc31c99a0ab4c153ff00b6414b8f527
Python 3.9.13, Qt 5.12.9, Coin 4.0.0, OCC 7.5.3
Locale: Polish/Poland (pl_PL)
```

If, in a tree view, I open the popup menu for this object to edit, I see an untranslated option label.

![obraz](https://user-images.githubusercontent.com/39754351/172018352-20fb6aea-a114-4763-a3b1-39d24bbb1509.png)

The message in the window appears to be constructed from several strings.
This case can also apply to other tools, e.g. fillet, chamfer, thickness etc.
The problem was found by david69 from the FreeCAD forum.

**Comment by chennes** [comment]
This is actually the same issue as #166 -- "Draft" is the name of the object, so this particular string is correct. It still leaves open the question of whether default object names should be translated, but since they technically lie outside the GUI I'm not sure if it's something we want to get into.
