### ISSUE TITLE
Missing task panel strings

### ISSUE THREAD

**Issue by cehjan** [FreeCAD/FreeCAD-translations#205]
I am translating FreeCAD into the Serbian language (Latin and Cyrillic) and I noticed that certain strings are missing from task panels.

Part Design workbench

Pad feature (Symmetric to plane, Reversed,)
![pad](https://user-images.githubusercontent.com/131595212/233968688-97455112-f732-4226-a6cd-b14f0641a462.jpg)

Revolve feature (Vertical sketch axis, Horizontal sketch axis, Select reference)
![revolve](https://user-images.githubusercontent.com/131595212/233968718-6fa07a2b-257d-4664-aade-84efe973407b.jpg)

Thickness feature (Preview)
![thickness](https://user-images.githubusercontent.com/131595212/233970305-d012b8b9-24b1-4747-b7de-0f6963655e4d.jpg)

Polar pattern parameters (Reverse direction)
![transformation](https://user-images.githubusercontent.com/131595212/233970324-f7f98edb-8230-45c5-94d1-85b779f5d4ce.jpg)

**Comment by kaktusus** [comment]
@cehjan 
I welcome you warmly to this corner for FreeCAD.

I have a request for you.

When you set up a new problem report try to provide as much information as possible that is useful to the programmer so that he does not spend too much attention to identify the problem.

I always provide the FC version on which I found the problem - I do updates very often.

And I provide links to Crowdin with the string to which the problem applies. This is very helpful to programmers. They can easily review this information and do not have to look for everything on their own.

Review old submissions you will see a certain pattern.

**Comment by kaktusus** [comment]
I noticed that some of your problems are due to some accident, for example the string `reverse direction` has 10 occurrences of which 9 have a hidden attribute. There are no translations in these items, so strings without translations are presented.

https://crowdin.com/translate/freecad/all/en-sr?filter=basic&value=0#q=reverse%20direction

I expect that there will be a lot of such cases because this is not a new problem.

To translate these strings you must ask for proofreader privileges or managers will fix this problem. The second solution will bring more benefits to many nations.

**Comment by kaktusus** [comment]
I can also help you in some cases.
Open a chat on Crowdin directly to me _`(_kaktus_)`_ and we will talk . You will have to lead me by the hand because I don't speak your language.
But we can fix it and you will be happy.
